# Generated by Django 5.2.4 on 2025-08-05 11:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
